sudo : required 
services:
  - docker 

before_install:
  - docker build --tag quer0/dupa -f Dockerfile.dev .

script:
  - docker run -e CI=true quer0/dupa npm run test

deploy:
  provider: elastickbeantalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env" 
  bucket_name: "elasticbeanstalk-us-east-2-102289334398"
  bucket_path: "docker"
  on:
    branch: master 

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
